In [1]:
#pip install pandas scikit-learn matplotlib seaborn

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('sales_data_sample.csv', encoding='ISO-8859-1')

In [15]:
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MSRP,PRODUCTCODE,STATUS_Disputed,STATUS_In Process,...,"CUSTOMERNAME_Tokyo Collectables, Ltd","CUSTOMERNAME_Toms Spezialitten, Ltd","CUSTOMERNAME_Toys of Finland, Co.",CUSTOMERNAME_Toys4GrownUps.com,"CUSTOMERNAME_UK Collectables, Ltd.","CUSTOMERNAME_Vida Sport, Ltd",CUSTOMERNAME_Vitachrome Inc.,"CUSTOMERNAME_Volvo Model Replicas, Co",CUSTOMERNAME_West Coast Collectables Co.,CUSTOMERNAME_giftsbymail.co.uk
0,10107,30,95.70,2,2871.00,1,95,S10_1678,False,False,...,False,False,False,False,False,False,False,False,False,False
1,10121,34,81.35,5,2765.90,2,95,S10_1678,False,False,...,False,False,False,False,False,False,False,False,False,False
2,10134,41,94.74,2,3884.34,3,95,S10_1678,False,False,...,False,False,False,False,False,False,False,False,False,False
3,10145,45,83.26,6,3746.70,3,95,S10_1678,False,False,...,False,False,False,True,False,False,False,False,False,False
4,10159,49,100.00,14,5205.27,4,95,S10_1678,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,4,54,S72_3212,False,False,...,False,False,False,False,False,False,False,False,False,False
2819,10373,29,100.00,1,3978.51,1,54,S72_3212,False,False,...,False,False,False,False,False,False,False,False,False,False
2820,10386,43,100.00,4,5417.57,1,54,S72_3212,False,False,...,False,False,False,False,False,False,False,False,False,False
2821,10397,34,62.24,1,2116.16,1,54,S72_3212,False,False,...,False,False,False,False,False,False,False,False,False,False
2822,10414,47,65.52,9,3079.44,2,54,S72_3212,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
df.nunique()

ORDERNUMBER          307
QUANTITYORDERED       58
PRICEEACH           1016
ORDERLINENUMBER       18
SALES               2763
ORDERDATE            252
STATUS                 6
QTR_ID                 4
MONTH_ID              12
YEAR_ID                3
PRODUCTLINE            7
MSRP                  80
PRODUCTCODE          109
CUSTOMERNAME          92
PHONE                 91
ADDRESSLINE1          92
ADDRESSLINE2           9
CITY                  73
STATE                 16
POSTALCODE            73
COUNTRY               19
TERRITORY              3
CONTACTLASTNAME       77
CONTACTFIRSTNAME      72
DEALSIZE               3
dtype: int64

In [6]:
df = df.drop(columns=['PHONE', 'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE', 'COUNTRY', 
                      'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'TERRITORY', 'YEAR_ID', 'MONTH_ID', 'ORDERDATE'])

In [7]:
df.isnull().sum()

ORDERNUMBER        0
QUANTITYORDERED    0
PRICEEACH          0
ORDERLINENUMBER    0
SALES              0
STATUS             0
QTR_ID             0
PRODUCTLINE        0
MSRP               0
PRODUCTCODE        0
CUSTOMERNAME       0
DEALSIZE           0
dtype: int64

In [8]:
X = df.drop('SALES', axis=1)  # Features
y = df['SALES']  # Target variable

In [9]:
X.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,STATUS,QTR_ID,PRODUCTLINE,MSRP,PRODUCTCODE,CUSTOMERNAME,DEALSIZE
0,10107,30,95.70,2,Shipped,1,Motorcycles,95,S10_1678,Land of Toys Inc.,Small
1,10121,34,81.35,5,Shipped,2,Motorcycles,95,S10_1678,Reims Collectables,Small
2,10134,41,94.74,2,Shipped,3,Motorcycles,95,S10_1678,Lyon Souveniers,Medium
3,10145,45,83.26,6,Shipped,3,Motorcycles,95,S10_1678,Toys4GrownUps.com,Medium
4,10159,49,100.00,14,Shipped,4,Motorcycles,95,S10_1678,Corporate Gift Ideas Co.,Medium

In [10]:
df = pd.get_dummies(df, columns=['STATUS', 'PRODUCTLINE', 'DEALSIZE', 'CUSTOMERNAME'], drop_first=True)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
# Create a linear regression model
model = LinearRegression()

# Train the model on the training data
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'Shipped'